export default {
  
    "login": "dev-adan",
    "id": 20452481,
    "node_id": "MDQ6VXNlcjIwNDUyNDgx",
    "avatar_url": "https://avatars.githubusercontent.com/u/20452481?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dev-adan",
    "html_url": "https://github.com/dev-adan",
    "followers_url": "https://api.github.com/users/dev-adan/followers",
    "following_url": "https://api.github.com/users/dev-adan/following{/other_user}",
    "gists_url": "https://api.github.com/users/dev-adan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dev-adan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dev-adan/subscriptions",
    "organizations_url": "https://api.github.com/users/dev-adan/orgs",
    "repos_url": "https://api.github.com/users/dev-adan/repos",
    "events_url": "https://api.github.com/users/dev-adan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dev-adan/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Adan Ali",
    "company": null,
    "blog": "",
    "location": "Pakistan",
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": "AdanaligakharVi",
    "public_repos": 7,
    "public_gists": 0,
    "followers": 1,
    "following": 6,
    "created_at": "2016-07-14T05:41:42Z",
    "updated_at": "2022-04-28T10:02:32Z"

    };

